# Generated by Django 4.1.3 on 2022-11-20 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_calendario_gasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='fecha',
        ),
        migrations.AddField(
            model_name='gasto',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
