# Generated by Django 4.1.3 on 2022-11-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_gasto_fecha_gasto_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
